language: java

os: linux

jdk:
  - openjdk8
  - oraclejdk8
  - openjdk9
  - oraclejdk9
  - openjdk10
  - oraclejdk10
  - openjdk11
  - oraclejdk11

cache:
  directories:
    - $HOME/.m2

script:
  - mvn compile
  - mvn test
  
after_success:
  - bash <(curl -s https://codecov.io/bash)